name: Docker Backend CI/CD

on:
  push:
    branches: [ main, master ]
    paths:
      - 'backend/**'
      - '.github/workflows/docker-backend.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  validate-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Check for required files
        run: |
          if [ ! -f "./backend/config/firebase.js" ]; then
            echo "Warning: firebase.js not found. This might cause issues in deployment."
          fi
          if [ ! -f "./backend/config/firebase-admin.js" ]; then
            echo "Warning: firebase-admin.js not found. This might cause issues in deployment."
          fi
          
  build-and-push:
    runs-on: ubuntu-latest
    needs: validate-env
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/artify-backend:latest,${{ secrets.DOCKERHUB_USERNAME }}/artify-backend:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/artify-backend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/artify-backend:buildcache,mode=max
